name: cafe-con-ia-daily
on:
  schedule:
    - cron: "30 11 * * *"   # 07:30 America/Toronto (EDT)
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: node index.js
        env:
          TZ: America/Toronto
          FEEDS: ${{ secrets.FEEDS }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
